#ifndef __LEPTON_SYS_H_
#define __LEPTON_SYS_H_

#define SYS 0x02

#define LEPTON_SYS_PING                          	0x0000
#define LEPTON_SYS_CAM_STATUS                    	0x0004
#define LEPTON_SYS_FLIR_SERIAL_NUMBER            	0x0008
#define LEPTON_SYS_CAM_UPTIME                    	0x000C
#define LEPTON_SYS_AUX_TEMPERATURE_KELVIN        	0x0010
#define LEPTON_SYS_FPA_TEMPERATURE_KELVIN        	0x0014
#define LEPTON_SYS_TELEMETRY_ENABLE_STATE        	0x0018
#define LEPTON_SYS_TELEMETRY_LOCATION           	0x001C
#define LEPTON_SYS_EXECTUE_FRAME_AVERAGE        	0x0020
#define LEPTON_SYS_NUM_FRAMES_TO_AVERAGE         	0x0024
#define LEPTON_SYS_CUST_SERIAL_NUMBER            	0x0028
#define LEPTON_SYS_SCENE_STATISTICS              	0x002C
#define LEPTON_SYS_SCENE_ROI                     	0x0030
#define LEPTON_SYS_THERMAL_SHUTDOWN_COUNT       	0x0034
#define LEPTON_SYS_SHUTTER_POSITION              	0x0038
#define LEPTON_SYS_FFC_SHUTTER_MODE_OBJ				0x003C
#define LEPTON_SYS_RUN_FFC_NORMALIZATION			0x0040
#define FLR_SYS_RUN_FFC                       		0x0042
#define LEPTON_SYS_FFC_STATUS                    	0x0044
#define LEPTON_SYS_GAIN_MODE                     	0x0048
#define LEPTON_SYS_FFC_STATE                     	0x004C
#define LEPTON_SYS_GAIN_MODE_OBJ                 	0x0050
#define LEPTON_SYS_GAIN_MODE_DESIRED_FLAG        	0x0054
#define LEPTON_SYS_BORESIGHT_VALUES              	0x0058


typedef enum
{
	LEPTON_SYS_STATUS_WRITE_ERROR = -2,
	LEPTON_SYS_STATUS_ERROR = -1,
	LEPTON_SYS_STATUS_READY = 0,
	LEPTON_SYS_STATUS_BUSY,
	LEPTON_SYS_FRAME_AVERAGE_COLLECTING_FRAMES,
	LEPTON_SYS_STATUS_END
}LEPTON_SYS_STATUS_E, *LEPTON_SYS_STATUS_E_PTR;

typedef struct
{
	LEPTON_SYS_STATUS_E camStatus;
	uint16_t commandCount;
	uint16_t reserved;
}LEPTON_STATUS_T, *LEPTON_STATUS_T_PTR;

typedef enum LEPTON_SYS_SHUTTER_POSITION_E_TAG
{
   LEPTON_SYS_SHUTTER_POSITION_UNKNOWN = -1,
   LEPTON_SYS_SHUTTER_POSITION_IDLE = 0,
   LEPTON_SYS_SHUTTER_POSITION_OPEN,
   LEPTON_SYS_SHUTTER_POSITION_CLOSED,
   LEPTON_SYS_SHUTTER_POSITION_BRAKE_ON,
   LEPTON_SYS_SHUTTER_POSITION_END

}LEPTON_SYS_SHUTTER_POSITION_E,  *LEPTON_SYS_SHUTTER_POSITION_E_PTR;

typedef enum LEPTON_SYS_FFC_SHUTTER_MODE_E_TAG
{
	LEPTON_SYS_FFC_SHUTTER_MODE_MANUAL = 0,
	LEPTON_SYS_FFC_SHUTTER_MODE_AUTO,
	LEPTON_SYS_FFC_SHUTTER_MODE_EXTERNAL,
	LEPTON_SYS_FFC_SHUTTER_MODE_END
}LEPTON_SYS_FFC_SHUTTER_MODE_E, *LEPTON_SYS_FFC_SHUTTER_MODE_E_PTR;

#endif
